// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    facilities_by_filter: {
        name: "facilities_by_filter";
        parameters: {
          /** STRING - use sql.string() */
          capability_substring: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          city: SQLStringMarker;
          /** INT - use sql.int() */
          row_limit: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          facility_id: string;
          /** @sqlType STRING */
          facility_name: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType STRING */
          description: string;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType STRING */
          equipment: string;
          /** @sqlType STRING */
          capability: string;
          /** @sqlType STRING */
          evidence_field: string;
        }>;
      };
    facility_detail: {
        name: "facility_detail";
        parameters: {
          /** STRING - use sql.string() */
          facility_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          facility_id: string;
          /** @sqlType STRING */
          facility_name: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          address_line1: string;
          /** @sqlType STRING */
          address_line2: string;
          /** @sqlType STRING */
          address_line3: string;
          /** @sqlType STRING */
          postcode: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType STRING */
          facility_type: string;
          /** @sqlType STRING */
          operator_type: string;
          /** @sqlType STRING */
          description: string;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType STRING */
          procedure: string;
          /** @sqlType STRING */
          equipment: string;
          /** @sqlType STRING */
          capability: string;
          /** @sqlType STRING */
          number_doctors: string;
          /** @sqlType STRING */
          capacity: string;
          /** @sqlType STRING */
          year_established: string;
          /** @sqlType STRING */
          phone: string;
          /** @sqlType STRING */
          website: string;
          /** @sqlType STRING */
          email: string;
          /** @sqlType STRING */
          source_urls: string;
        }>;
      };
    states: {
        name: "states";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
  }
}
